backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Give a brief overview of what you will cover", name: "description", widget: "text"}
      - {label: "Header Image", name: "header", widget: "file"}
      - {label: "Youtube URL", name: "youtubeLink", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/resources/index.md"
        label: "Resources Page"
        name: "resources"
        create: true
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "resource-page"}
          - {label: Title, name: title, widget: string}
          - {label: Header Image, name: header_image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Resource, name: resource, widget: list, fields: [{label: Resource Name, name: resourceName, widget: string}, {label: Resource Description, name: resourceDescription, widget: string}, {label: Resource Price, name: resourcePrice, widget: string}, {label: Resource Download or Purchase URL, name: resourceURL, widget: string}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
      - file: "src/pages/home.md"
        label: "Home Page"
        name: "home"
        create: true
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page"}
          - {label: Title, name: title, widget: string}
          - {label: Header Image, name: home_image, widget: image}
          - {label: Body Content, name: home_content, widget: markdown}
      
  - name: "authors"
    label: "Authors"
    folder: "src/pages/authors"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "author-post"}
      - {label: "Name", name: "authorName", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Quick blurb about yourself (1 sentence max)", name: "authorDescription", widget: "text"}
      - {label: "Header Image", name: "coverImage", widget: "file"}
      - {label: "Square Profile Image", name: "profileImage", widget: "file"}
      - {label: "Main Social Profile URL", name: "socialLink", widget: "string"}
      - {label: "Tell Us About Yourself", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}
      - {label: "Recommended Reading", name: "authorRecommended", widget: "string"}
      - {label: "Recommended Reading Image", name: "authorRecommendedImage", widget: "file"}

  