backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Give a brief overview of what you will cover", name: "description", widget: "text"}
      - {label: "Header Image", name: "header", widget: "file"}
      - {label: "Youtube URL", name: "youtubeLink", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about-page"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Wide Image", name: "full_image", widget: file}

      - file: "src/pages/jargon/index.md"
        label: "Jargon"
        name: "jargon"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Wide Image", name: "full_image", widget: file}

      - file: "src/pages/resources/index.md"
        label: "Resources Page"
        name: "resources"
        create: true
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "resource-page"}
          - {label: Title, name: "title", widget: string}
          - {label: Header Image, name: "image", widget: file}
          - {label: Description, name: "description", widget: string}
          - {label: Resource, name: "resource", widget: list, fields: [{label: Resource Name, name: resourceName, widget: string}, {label: Resource Description, name: resourceDescription, widget: string}, {label: Resource Image, name: resourceImage, widget: image}, {label: Resource Price, name: resourcePrice, widget: string}, {label: Resource Download or Purchase URL, name: resourceURL, widget: string}]}
          - {label: Full Image, name: "fullImage", widget: file}
          
      - file: "src/pages/home.md"
        label: "Home Page"
        name: "home"
        create: true
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page"}
          - {label: Title, name: title, widget: string}
          - {label: Header Image, name: "homeImage", widget: image}
          - {label: Body Content, name: "homeContent", widget: markdown}
      
      - file: "src/pages/lisa/index.md"
        label: "Lisa Profile"
        name: "lisa"
        create: true
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "home-page"}
          - {label: "Name", name: "title", widget: string}
          - {label: "Wide Image", name: "full_image", widget: file}
          - {label: "Body", name: "body", widget: "markdown"}
      
  

  